version: '3.8'

services:
  hexagonal:
    image: postgres:latest
    container_name: hexagonal-api-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hexagonal
    ports:
      - '5432:5432'
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U hexagonal' ]
      interval: 10s
      timeout: 5s
      retries: 5
